name: Deploy to Cloud Run

on:
  push:
    branches:
      - prod

env:
  PROJECT_ID: civicpulse-500507
  SERVICE: civicpulse
  REGION: asia-south1
  IMAGE: asia-south1-docker.pkg.dev/civicpulse-500507/civicpulse-repo/civicpulse

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/948264080742/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-sa@civicpulse-500507.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE }}:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE }}:${{ github.sha }}
          flags: '--allow-unauthenticated'
